# Generated by Django 3.2.5 on 2021-07-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210728_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_folllows',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
